### ISSUE TITLE
VtkViewerColouredNew does not apply materialVisOptions

### ISSUE THREAD

**Issue by ManuelHu** [g4edge/pyg4ometry#106]
This works in the old vtk viewer (the geometry has a volume `lar` made of `LiquidArgon`):
```py
v = visualisation.VtkViewerColoured(materialVisOptions={"LiquidArgon":[0,0,0,0.05]})
v.addLogicalVolume(registry.worldVolume)
v.view()
```

but in the new viewer, I somehow have to set the `instanceVisOptions` manually - so apparently the `materialVisOptions` are not propagated correctly:
```py
v = visualisation.VtkViewerColouredNew(materialVisOptions={"LiquidArgon":[0,0,0,0.05]})
v.addLogicalVolume(registry.worldVolume)
v.instanceVisOptions['lar'][0].alpha = 0.05 # <--- I have to add this line for each volume to affect the rendering
v.buildPipelinesAppend()
v.view()
```
but then the colors get applied correctly, so that part works at least :-) Or is this new behavior expected?

**Comment by stewartboogert** [comment]
Sorry somehow I missed this issue. I'll check if I propagate the material vis options.
