### ISSUE TITLE
Viewer Bug - EllipticalTube viewed incorrectly in pyg4ometry viewer (half axis / full axis mix up)

### ISSUE THREAD

**Issue by FlorianStummer** [g4edge/pyg4ometry#162]
The EllipticalTube object is viewed half as big as it should be according to the GDML (for all x/y/z). Probably a factor 1/2 missing somewhere in the pyg4ometry definition.
<img width="1206" alt="Screenshot 2024-06-27 at 22 29 06" src="https://github.com/g4edge/pyg4ometry/assets/70774022/de4caf6c-ecb8-4a15-b602-80b36ad32feb">
[error.zip](https://github.com/user-attachments/files/16021029/error.zip)

**Comment by stewartboogert** [comment]
Should be any easy enough fix. Can you post your test (python) file here for me to text against

**Comment by FlorianStummer** [comment]
A quick test that recreates the problem is in in the zip file attached (below the image)

**Comment by stewartboogert** [comment]
Fixed with #168
