### ISSUE TITLE
Unit handling is insufficient

### ISSUE THREAD

**Issue by ManuelHu** [g4edge/pyg4ometry#175]
At the moment, the [provided unit list](
https://github.com/g4edge/pyg4ometry/blob/e3e75fe38382a1293a8e6b07da2847e3d1e32dbf/src/pyg4ometry/gdml/Units.py) is incomplete and used inconsistently:

* a lot of units and unit aliases are missing, i.e. `nanometer` (and many more).
* `in` does not appear to be in `setSystemOfUnits.cc` in CLHEP (it also is not a valid unit in `G4UnitsTable.cc`; why is it there?) @stewartboogert added it in 091b48654d5f67491817cd7ddd4b78e3b1630a7d
* The unit values do not match the equivalent in Geant4 (but that might not matter a lot?)

**Comment by stewartboogert** [comment]
Agreed we should improve the units. Is only the extension of units dict? 

One way would be to write a script but there is very little change to geant4 units and would we get value out of a automatic conversion script vs just updating

I added inch for some US experiment, I would have never included it, if it didn't work.

**Comment by ManuelHu** [comment]
> One way would be to write a script but there is very little change to geant4 units and would we get value out of a automatic conversion script vs just updating

Agreed. I wrote a very crude script to do the initial conversion in #176, but this is certainly not ready to be used automatically, and still required some manual editing afterwards :-)

> I added inch for some US experiment, I would have never included it, if it didn't work.

Thats interesting. At least G4 11.2 fails with a solid that has `lunit="in"` and with material properties that use `*in` in their expression. Maybe I was testing it wrong? Or another GDML-consuming application does accept it?

**Comment by stewartboogert** [comment]
Ok Manuel. You happy to proceed updating the units? I think it is worthwhile and should really not take that long.

**Comment by ManuelHu** [comment]
Yes, I can proceed on my PR :-)
I can also add back inch for the moment; the failure of G4 reading this is very prominent and immediately when reading the GDML, so there is at least no possibility of subtle data loss/malfunction...
