### ISSUE TITLE
precommit actions

### ISSUE THREAD

**Issue by lnevay** [g4edge/pyg4ometry#202]
Do we have to really have the precommit actions for every single commit?  It really makes it a misery to develop and commit changes.  Fine for these to run automatically say before I want to do a pull request, but at every single commit is quite annoying.

I also got stuck because the checks used for formatting require the very latest "identify" package from Sep 2024.  This actually prevented me from committing. Even when it does work it takes minutes to make a commit.

**Comment by ManuelHu** [comment]
The pre-commit rules are already checked for pull requests and also for direct pushes.

If and how you run pre-commit locally is (technically) up to you; and cannot be configured as part of the pre-commit config here on github.

For my part: I usually run pre-commit while developing features, but I do not add it as an actual git hook.

**Comment by gipert** [comment]
I think the whole point of pre-commit is to run it for every commit, such that all commits are consistent between each other in terms of formatting. Having, say, 10 commits and a pre-commit one at the end doesn't make sense from the point of view of Git history. For the same reason we should actually be more picky are reject PRs including the automatic pre-commit commits: commits that fail pre-commit checks should not be par of pyg4ometry's Git history.

I'm surprised to hear that it takes so long to run the checks locally, it's typically fast. Maybe the Clang checks are the slowest but they are also only triggered by changes to the C++ extensions. 

So we need to figure out what's the issue in your local environment. Which check is the responsible? I don't know what you mean with this "identify" package.

**Comment by lnevay** [comment]
Well isn't it that there is a `.pre-commit-config.yaml` defined in the repository, so `git commit` will always run this. To avoid it you have to do `git commit --no-verify...`.

My point is this is a real hindrance and too heavy.  Why not use pre-receive or pre-push?

Fine about enforcing formatting of say the commit message. But checking the whole code for code-formatting can be done once before a push really.

**Comment by gipert** [comment]
> Well isn't it that there is a .pre-commit-config.yaml defined in the repository, so git commit will always run this. To avoid it you have to do git commit --no-verify....

Nope, you have to explicitly run `pre-commit install` once at the beginning for that (installs the Git hook Manuel was talking about). The default is to not run pre-commit automatically, you can uninstall the Git hook by running `pre-commit uninstall`.

> Fine about enforcing formatting of say the commit message. But checking the whole code for code-formatting can be done once before a push really.

Also this should not happen. Unless you specify `--all-files`, pre-commit will check only files that have been modified.

**Comment by stewartboogert** [comment]
Ok @lnevay the pre commit linting and reformatting will run when you make a PR. So you don't have to run it for every commit. But I will probably squash merge your PRs. No real problem either way. Closing the issue. 

Closing the issue
