### ISSUE TITLE
Use something other than Black / Undo Huge Edits to Code

### ISSUE THREAD

**Issue by lnevay** [g4edge/pyg4ometry#60]
The use of black formatting has made the code really hard to read and debug.  I'm all for consistency but this specific style adds lots of extra lines and has really horrible unnecessary wrapping of things. It might be a popular style but it's making contributing to pyg4ometry and debugging it a truly difficult and miserable experience. It also means inspecting the history is useless now in an easy way as we have impassible commits for formatting.

There are bonus commas everywhere where there really shouldn't be and the wrapping puts parenthesis at the wrong level of indentation.

It's really distracting and frustrating.  I have to edit the code to see what arguments to where as it's just unreadable and then I can watch as it all gets undone perversely.

**Comment by lnevay** [comment]
This helps a lot but again has created an impassable commit that touches every line of the code. The specific black style is still really horrific and really unreadable for me but this at least has made it significantly more liveable.  Below is an example of how it wraps things that would easily fit inside the line limit length.  It's like 1990s C style.

```
        elif isinstance(var, _Defines.ScalarBase):  # a normal expression
            for v in var.expression.variables(
                True
            ):  # loop over all variables needed for an expression
                if v in otherRegistry.defineDict:  # only if it's in the other registry
                    self.transferDefine(
                        otherRegistry.defineDict[v], incrementRenameDict, userRenameDict
                    )
            if (
                var.name in otherRegistry.defineDict
            ):  # check if variable is stored in registry, if so need to be transferred
                self.transferDefine(
                    var, incrementRenameDict, userRenameDict
                )  # probably best to reuse here
```      

Another example:
```
            # add members from physical volume
            self.transferDefines(
                volume.position, volume.registry, incrementRenameDict, userRenameDict
            )
            self.transferDefines(
                volume.rotation, volume.registry, incrementRenameDict, userRenameDict
            )
            if volume.scale:
                self.transferDefines(
                    volume.scale, volume.registry, incrementRenameDict, userRenameDict
                )
            self.transferPhysicalVolume(volume, incrementRenameDict, userRenameDict)
```
vs
```
            # add members from physical volume
            self.transferDefines(volume.position, volume.registry, incrementRenameDict, userRenameDict)
            self.transferDefines(volume.rotation, volume.registry, incrementRenameDict, userRenameDict)
            if volume.scale:
                self.transferDefines(volume.scale, volume.registry, incrementRenameDict, userRenameDict)
            self.transferPhysicalVolume(volume, incrementRenameDict, userRenameDict)
```
infinitely more readable and 5 vs 11 lines to look through.

**Comment by lnevay** [comment]
I would actually advocate we rebase recent merge requests earlier before all this was done to undo it. I can live with slightly inconsistent code formatting if it means the git history is useable and the code is infinitely more readable.  It's truly jarring.  I regularly use the history of which line was edited in which commit much more than adhering to a particular style.  The codebase before wasn't actually too inconsistent in style.

**Comment by stewartboogert** [comment]
Close with #72
