### ISSUE TITLE
Re-add former pyg4ometry tags

### ISSUE THREAD

**Issue by lnevay** [g4edge/pyg4ometry#61]
Somehow in the recent shift to github and surprise renaming of the branches the version numbers are wrong. When installing pyg4ometry locally it is 0.1.dev2875+g4b48afa  for example.  I see that all tags have been deleted too.  I would really like us to bring these back if possible.  I have no idea how they were all deleted in the first place though.

**Comment by gipert** [comment]
Setuptools implements version string specifiers as per [PEP 440](https://peps.python.org/pep-0440). There are not tags in this repo at the moment, so the assumption is that the next tag will be `0.1`.

I'm not sure why git filter-repo did not preserve existing tags, but it might be in general a tricky thing to do when rewriting history.

I can push the 1.0.5 tag (this commit: 4d9afcf419c3318930d9265570eea9b5e70a37fb), if you want. Then the dev version string will be relative to that and will make more sense. We can certainly also re-add all the remaining tags.

**Comment by stewartboogert** [comment]
@lnevay  So following discussion with @gipert. We have looked though the distribution with a creation of a tag. A lot has changed and been updated so the next tag will be `1.1`. This trigger the build, wheel creation and upload to pypi.

We could put the old tags back as @gipert said, but right now lets concentrate on getting the current version available to users.

**Comment by gipert** [comment]
I have pushed v1.0.5: https://github.com/g4edge/pyg4ometry/releases/tag/v1.0.5

**Comment by stewartboogert** [comment]
I think this issue is closed as I don't think going back further is tags is useful

**Comment by lnevay** [comment]
I actually tried to transfer them as I think not great to just dump history, but all the commits that correspond to tags are actually missing from the new repository. In some cases the history doesn't go that far back in the new repository. In others, the directory that was in the commit that was tagged has gone, so so has the commit (e.g. the paper submission tag on pyg4ometry/public/paper).

**Comment by lnevay** [comment]
Agreed it should be the second number that changes in the next version. Many of the past versions were not patches (third number) but changes of interface.
