### ISSUE TITLE
Fluka reader transforms not working

### ISSUE THREAD

**Issue by stewartboogert** [g4edge/pyg4ometry#65]
There appears to be an asymmetry in the FLUKA reader. 

``body.transform`` should be of type `` RecursiveRTrans`` but find it is ``pyg4ometry.fluka.directive.Transform``

Our current workflows are 
- load geant4 and convert to fluka (this all works and the transform is ``RecursiveRTrans``)
- writing python generated fluka (does not test transformations)
- import fluka and convert to geant4
- import fluka and view

**Comment by lnevay** [comment]
We actually noticed that exported geometry with gdml 'scale' (ie reflections in pvs) isn't working.  Was going to investigate today.

**Comment by stewartboogert** [comment]
There appears to be classes with overlapping functionality ``fluka.directive`` has 

- ``Transform``
- ``RotoTranslation``
- ``RecursiveRotoTranslation``

For sure if ``RotoTranslation`` is used it does work. I have added but not made the PR for ``Transform.rotoTranslation``. ``Transform`` contains separate lists of 

- ``expansion`` so scale
- ``translation`` just translation and
- ``rotoTranslation`` 

So right now ``expansion`` and ``translation`` are not written in the FLUKA output. Follow this issue for progress

**Comment by stewartboogert** [comment]
> We actually noticed that exported geometry with gdml 'scale' (ie reflections in pvs) isn't working. Was going to investigate today.

This is a separate issue #81

**Comment by stewartboogert** [comment]
Fixed in #83
