### ISSUE TITLE
Problem uploading to pypi

### ISSUE THREAD

**Issue by stewartboogert** [g4edge/pyg4ometry#77]
distribute workflow failed with the following warning

```
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Invalid or non-existent authentication information. See                
         https://pypi.org/help/#invalid-auth for more information. 
```

**Comment by gipert** [comment]
can you add me to the pypi project? I am gipert there too

**Comment by stewartboogert** [comment]
> can you add me to the pypi project? I am gipert there too

Done

**Comment by gipert** [comment]
I re-generated the token, works now: 

https://github.com/g4edge/pyg4ometry/actions/runs/5766498198/job/15644994202
https://pypi.org/project/pyg4ometry/
