### ISSUE TITLE
Build doesn't work offline

### ISSUE THREAD

**Issue by lnevay** [g4edge/pyg4ometry#84]
If you have all the dependencies and the repository you can't install the package locally without internet connection it would seem.

```pip install --editable .```

<img width="1250" alt="Screenshot 2023-08-06 at 18 25 59" src="https://github.com/g4edge/pyg4ometry/assets/9283103/478e443f-5ae1-45ba-b6f6-2cde0bc4a937">

**Comment by ManuelHu** [comment]
Can you try if
```
pip install --no-build-isolation --editable .
```
fixes your build? I had success with it (for other python packages, but also in a container without network access). If this is the case, the build failure without network is expected by PEP-517

**Comment by gipert** [comment]
Thanks @ManuelHu!
