### ISSUE TITLE
Defines Aren't Used in GDML

### ISSUE THREAD

**Issue by lnevay** [g4edge/pyg4ometry#85]
A recent change has made it so that defines are not used by name in exported GDML but rather their value is given. For example, I commonly do:

```
self._twopi = _gd.Defines.Constant("twopi", "2*pi", self.registry)
```
in classes I create to construction geometry, then use the object `_twopi` in the constructor of say a Tubs. When written out to GDML now, I see "2*pi" instead of "twopi" in the value of the parameter in the solid definition.

**Comment by stewartboogert** [comment]
Bug introduced in `fc0fac5` when expressions were refactored @lnevay 

Fix is simple and in #85
